terminal:
  colorScheme:
    name: My_dark
    foreground: '#eceff1'
    background: 'rgba(0, 0, 0, 0.4)'
    selection: null
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  font: Cascadia Code Regular
  ligatures: true
  cursor: block
  fallbackFont: MesloLGS NF Regular
  fontSize: 14
  environment: {}
  useConPTY: true
  bell: 'off'
  pasteOnMiddleClick: true
  profile: wsl-/-arch
  workingDirectory: ''
  frontend: xterm
  customColorSchemes:
    - name: My_dark
      foreground: '#eceff1'
      background: 'rgba(0, 0, 0, 0.4)'
      selection: null
      cursor: '#FFCC00'
      colors:
        - '#000000'
        - '#D62341'
        - '#9ECE58'
        - '#FAED70'
        - '#396FE2'
        - '#BB80B3'
        - '#2DDAFD'
        - '#d0d0d0'
        - 'rgba(255, 255, 255, 0.2)'
        - '#FF5370'
        - '#C3E88D'
        - '#FFCB6B'
        - '#82AAFF'
        - '#C792EA'
        - '#89DDFF'
        - '#ffffff'
  background: colorScheme
hotkeys:
  shell: {}
  profile: {}
  home: []
  end: []
  previous-word: []
  next-word: []
serial: {}
appearance:
  vibrancyType: blur
  tabsLocation: top
  frame: thin
  css: |-
    /* * { color: blue !important; } */
    tab-body {
    background: rgba(0,0,0,0)
    }
  theme: Standard
  vibrancy: true
  opacity: 1
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - serial
